import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  build: [{type: 'autogenerated', dirName: 'build'}],
  run: [{type: 'autogenerated', dirName: 'run-node'}],
  learn: [{type: 'autogenerated', dirName: 'learn'}],
  "blockchain-users": [{type: 'autogenerated', dirName: 'blockchain-users'}]
};

export default sidebars;
