/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Quilibrium Docs",
  "tagline": "Learn how to get started building on the network, run a node, or just understand the technology",
  "favicon": "img/favicon.png",
  "url": "https://docs.quilibrium.com",
  "baseUrl": "/",
  "customFields": {
    "apiTesterEnabled": false
  },
  "organizationName": "QuilibriumNetwork",
  "projectName": "docs",
  "onBrokenAnchors": "throw",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "onDuplicateRoutes": "throw",
  "trailingSlash": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/QuilibriumNetwork/docs/tree/main/"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    null,
    "/home/vincit/dev/repos/q-docs/node_modules/docusaurus-lunr-search/src/index.js"
  ],
  "themeConfig": {
    "image": "img/socialcard-docs.png",
    "navbar": {
      "title": "Quilibrium Docs",
      "logo": {
        "alt": "Quilibrium Logo",
        "src": "img/q-symbol.png",
        "srcDark": "img/q-symbol.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "discover",
          "position": "left",
          "label": "Discover"
        },
        {
          "type": "docSidebar",
          "sidebarId": "learn",
          "position": "left",
          "label": "Learn"
        },
        {
          "type": "docSidebar",
          "sidebarId": "build",
          "position": "left",
          "label": "Build"
        },
        {
          "type": "docSidebar",
          "sidebarId": "protocol",
          "position": "left",
          "label": "Protocol"
        },
        {
          "type": "docSidebar",
          "sidebarId": "run",
          "position": "left",
          "label": "Run"
        },
        {
          "type": "docSidebar",
          "sidebarId": "api",
          "position": "left",
          "label": "API"
        },
        {
          "label": "Quilibrium Website",
          "href": "https://quilibrium.com",
          "position": "right"
        },
        {
          "label": "Code",
          "href": "https://github.com/QuilibriumNetwork",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Discover Q",
              "to": "/docs/discover/FAQ/"
            },
            {
              "label": "Learn Q",
              "to": "/docs/learn/block-storage/"
            },
            {
              "label": "Build Applications",
              "to": "/docs/category/applications"
            },
            {
              "label": "API Docs",
              "to": "/docs/api/overview"
            },
            {
              "label": "Run a Node",
              "to": "/docs/run-node/quick-start"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discourse Forum",
              "href": "https://discourse.quilibrium.com/"
            },
            {
              "label": "Farcaster",
              "href": "https://warpcast.com/~/channel/quilibrium"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Quilibrium Website",
              "href": "https://quilibrium.com"
            },
            {
              "label": "Blog",
              "href": "https://paragraph.xyz/@quilibrium.com"
            },
            {
              "label": "X",
              "href": "https://x.com/QuilibriumInc"
            },
            {
              "label": "Code",
              "href": "https://github.com/QuilibriumNetwork"
            }
          ]
        }
      ],
      "copyright": "\nCopyright © 2025 Quilibrium, Inc. <span>Licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">CC BY-SA 4.0.</a></span></br>\nBuilt with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
